/* Author:          ezhex1991@outlook.com
 * CreateTime:      2018-04-18 17:02:37
 * Organization:    #ORGANIZATION#
 * Description:     
 */
using UnityEngine;

namespace EZhex1991.EZUnity
{
    public enum EZKeyCode
    {
        None = KeyCode.None,

        Alpha_Alpha0 = KeyCode.Alpha0,
        Alpha_Alpha1 = KeyCode.Alpha1,
        Alpha_Alpha2 = KeyCode.Alpha2,
        Alpha_Alpha3 = KeyCode.Alpha3,
        Alpha_Alpha4 = KeyCode.Alpha4,
        Alpha_Alpha5 = KeyCode.Alpha5,
        Alpha_Alpha6 = KeyCode.Alpha6,
        Alpha_Alpha7 = KeyCode.Alpha7,
        Alpha_Alpha8 = KeyCode.Alpha8,
        Alpha_Alpha9 = KeyCode.Alpha9,
        Alpha_A = KeyCode.A,
        Alpha_B = KeyCode.B,
        Alpha_C = KeyCode.C,
        Alpha_D = KeyCode.D,
        Alpha_E = KeyCode.E,
        Alpha_F = KeyCode.F,
        Alpha_G = KeyCode.G,
        Alpha_H = KeyCode.H,
        Alpha_I = KeyCode.I,
        Alpha_J = KeyCode.J,
        Alpha_K = KeyCode.K,
        Alpha_L = KeyCode.L,
        Alpha_M = KeyCode.M,
        Alpha_N = KeyCode.N,
        Alpha_O = KeyCode.O,
        Alpha_P = KeyCode.P,
        Alpha_Q = KeyCode.Q,
        Alpha_R = KeyCode.R,
        Alpha_S = KeyCode.S,
        Alpha_T = KeyCode.T,
        Alpha_U = KeyCode.U,
        Alpha_V = KeyCode.V,
        Alpha_W = KeyCode.W,
        Alpha_X = KeyCode.X,
        Alpha_Y = KeyCode.Y,
        Alpha_Z = KeyCode.Z,

        Function_Escape = KeyCode.Escape,
        Function_F1 = KeyCode.F1,
        Function_F2 = KeyCode.F2,
        Function_F3 = KeyCode.F3,
        Function_F4 = KeyCode.F4,
        Function_F5 = KeyCode.F5,
        Function_F6 = KeyCode.F6,
        Function_F7 = KeyCode.F7,
        Function_F8 = KeyCode.F8,
        Function_F9 = KeyCode.F9,
        Function_F10 = KeyCode.F10,
        Function_F11 = KeyCode.F11,
        Function_F12 = KeyCode.F12,
        Function_F13 = KeyCode.F13,
        Function_F14 = KeyCode.F14,
        Function_F15 = KeyCode.F15,
        Function_Print = KeyCode.Print,
        Function_ScrollLock = KeyCode.ScrollLock,
        Function_Pause = KeyCode.Pause,
        Function_Break = KeyCode.Break,

        Keypad_Numlock = KeyCode.Numlock,
        Keypad_KeypadPeriod = KeyCode.KeypadPeriod,
        Keypad_KeypadDivide = KeyCode.KeypadDivide,
        Keypad_KeypadMultiply = KeyCode.KeypadMultiply,
        Keypad_KeypadMinus = KeyCode.KeypadMinus,
        Keypad_KeypadPlus = KeyCode.KeypadPlus,
        Keypad_KeypadEnter = KeyCode.KeypadEnter,
        Keypad_KeypadEquals = KeyCode.KeypadEquals,
        Keypad_Keypad0 = KeyCode.Keypad0,
        Keypad_Keypad1 = KeyCode.Keypad1,
        Keypad_Keypad2 = KeyCode.Keypad2,
        Keypad_Keypad3 = KeyCode.Keypad3,
        Keypad_Keypad4 = KeyCode.Keypad4,
        Keypad_Keypad5 = KeyCode.Keypad5,
        Keypad_Keypad6 = KeyCode.Keypad6,
        Keypad_Keypad7 = KeyCode.Keypad7,
        Keypad_Keypad8 = KeyCode.Keypad8,
        Keypad_Keypad9 = KeyCode.Keypad9,

        Punctuation_Exclaim = KeyCode.Exclaim,
        Punctuation_At = KeyCode.At,
        Punctuation_Hash = KeyCode.Hash,
        Punctuation_Dollar = KeyCode.Dollar,
        Punctuation_Caret = KeyCode.Caret,
        Punctuation_Ampersand = KeyCode.Ampersand,
        Punctuation_Asterisk = KeyCode.Asterisk,
        Punctuation_LeftParen = KeyCode.LeftParen,
        Punctuation_RightParen = KeyCode.RightParen,
        Punctuation_Minus = KeyCode.Minus,
        Punctuation_Underscore = KeyCode.Underscore,
        Punctuation_Equals = KeyCode.Equals,
        Punctuation_Plus = KeyCode.Plus,
        Punctuation_LeftBracket = KeyCode.LeftBracket,
        Punctuation_RightBracket = KeyCode.RightBracket,
        Punctuation_Backslash = KeyCode.Backslash,
        Punctuation_Semicolon = KeyCode.Semicolon,
        Punctuation_Colon = KeyCode.Colon,
        Punctuation_Quote = KeyCode.Quote,
        Punctuation_BackQuote = KeyCode.BackQuote,
        Punctuation_DoubleQuote = KeyCode.DoubleQuote,
        Punctuation_Comma = KeyCode.Comma,
        Punctuation_Less = KeyCode.Less,
        Punctuation_Period = KeyCode.Period,
        Punctuation_Greater = KeyCode.Greater,
        Punctuation_Slash = KeyCode.Slash,
        Punctuation_Question = KeyCode.Question,
        Punctuation_Space = KeyCode.Space,

        Edit_Insert = KeyCode.Insert,
        Edit_Delete = KeyCode.Delete,
        Edit_Home = KeyCode.Home,
        Edit_End = KeyCode.End,
        Edit_PageUp = KeyCode.PageUp,
        Edit_PageDown = KeyCode.PageDown,
        Edit_UpArrow = KeyCode.UpArrow,
        Edit_DownArrow = KeyCode.DownArrow,
        Edit_RightArrow = KeyCode.RightArrow,
        Edit_LeftArrow = KeyCode.LeftArrow,
    }
}
